### ISSUE TITLE
Wrong HTTP verb used for subscription management endpoints

### ISSUE THREAD

**Issue by tolu-paystack** [PaystackOSS/openapi#14]
The [endpoint for generating subscription management links](https://github.com/PaystackOSS/openapi/blob/main/main/resources/subscription/manage-link.yaml) is a `POST` endpoint in the OpenAPI spec, but it should be `GET`

<img width="523" alt="Screenshot 2022-08-03 at 20 57 49" src="https://user-images.githubusercontent.com/60101507/182698196-92b6ecc4-98dc-4d9c-85ac-33be57a5fd04.png">

**Comment by damilola-paystack** [comment]
Pull request #16 fixes this issue
