### ISSUE TITLE
Bug - update type of field

### ISSUE THREAD

**Issue by akinmail** [PaystackOSS/openapi#29]
https://github.com/PaystackOSS/openapi/blob/e65c07ce33d6900becd5f8dc3b935e7536ce486f/sdk/paystack.yaml#L3477 

According to the documentation [here](https://paystack.com/docs/api/plan#create), description is string and not boolean

**Comment by damilola-paystack** [comment]
Thanks for reporting this. An update will be made in a moment

**Comment by damilola-paystack** [comment]
PR #33 fixes this. Thanks for bringing it to our notice.
