### ISSUE TITLE
[Enhancement Request] Introduce a toggle for Disabling Cloudflare Turnstile / Google reCaptcha in both Sandbox and Production environments

### ISSUE THREAD

**Issue by angad777** [PaystackOSS/openapi#41]
**Is your feature request related to a problem? Please describe.**

We are encountering challenges while testing our payment gateway integration in both sandbox and production environments using Cypress. Due to the fact that Cypress can be identified as a bot by Cloudflare / Google, it hinders our testing process. To address this issue, we propose the implementation of a toggle feature in the PayStack admin dashboard. This toggle should have the capability to bypass Cloudflare Turnstile / Google reCaptcha, specifically designed for select accounts.

**Describe the solution you'd like**

Our preferred solution involves the addition of a toggle within the PayStack dashboard. This toggle should offer the flexibility to be enabled or disabled based on the testing requirements. When activated, it should effectively bypass Cloudflare Turnstile or Google reCaptcha, streamlining the testing process for select accounts and ensuring a smoother integration testing experience with Cypress.

**Additional context**

<img width="1440" alt="242406e5-2cc4-424d-9c0d-1688eb0f042d" src="https://github.com/PaystackOSS/openapi/assets/39453522/cc6782f2-e3da-4f42-a68a-4eedeacc37be">

**Comment by damilola-paystack** [comment]
Hey @angad777 this is an interesting suggestion. Let me liaise with the team and get back to you.
